#!/bin/sh

export CL_EXTERNAL_IP=13.52.246.74 && \
export CL_KEYSTORE=./key.p12 && \
export CL_PASSWORD=password && \
export CL_KEYALIAS=keyalias && \
export CL_APP_ENV=testnet && \
export CL_PUBLIC_HTTP_PORT=9000 && \
export CL_P2P_HTTP_PORT=9001 && \
export CL_CLI_HTTP_PORT=9002 && \
rollback_snapshot=`head -1 /home/admin/tessellation/rollback-snapshot` && \
java "-Xms1024M" "-Xmx3G" "-Xss256K" -jar /home/admin/tessellation/cl-node.jar run-rollback $rollback_snapshot --collateral 0 --seedlist /home/admin/tessellation/testnet-seedlist
