#!/bin/sh

export CL_EXTERNAL_IP=${public_ip} && \
export CL_KEYSTORE=./key.p12 && \
export CL_PASSWORD=password && \
export CL_KEYALIAS=keyalias && \
export CL_APP_ENV=${app_env} && \
export CL_PUBLIC_HTTP_PORT=${public_port} && \
export CL_P2P_HTTP_PORT=${p2p_port} && \
export CL_CLI_HTTP_PORT=${cli_port} && \
export CL_SNAPSHOT_STORED_PATH=${snapshot_stored_path} && \
rollback_snapshot=`head -1 /home/admin/tessellation/l0/rollback-snapshot` && \
java "-Xms1024M" "-Xmx3G" "-Xss256K" -jar /home/admin/tessellation/l0/cl-node.jar run-rollback $rollback_snapshot --collateral 0 --seedlist /home/admin/tessellation/l0/${app_env}-seedlist
