#!/usr/bin/env bash

red='\033[1;31m'
blu='\033[1;36m'
clr='\033[0m'

echo -e "$${blu}[Tessellation]$${clr} CRON setup started..." && \

incrontab -l > incron_bkp && \
echo "/home/${user}/tessellation/l0/${snapshot_stored_path} IN_CREATE,IN_MODIFY flock -n /var/lock/snapshots-s3-sync.lock /home/${user}/tessellation/l0/snapshots-s3-sync" >> incron_bkp && \
incrontab incron_bkp && \
rm -f incron_bkp && \

echo -e "$${blu}[Tessellation]$${clr} CRON setup succeeded" || \
echo -e "$${red}[Tessellation]$${clr} CRON setup failed!"
