#!/bin/sh

incrontab -l > incron_bkp
echo "/home/admin/tessellation/${snapshot_stored_path} IN_CREATE,IN_MODIFY /bin/bash /home/admin/tessellation/snapshots-s3-sync" >> incron_bkp
incrontab incron_bkp
rm -f incron_bkp
