#!/usr/bin/env bash

red='\033[1;31m'
blu='\033[1;36m'
clr='\033[0m'

set -e

echo -e "$${blu}[Tessellation]$${clr} Node setup started..." && \
echo -e "$${blu}[Tessellation]$${clr} Creating directories" && \

mkdir -p /tmp/tessellation/l1 && \
mkdir -p /tmp/tessellation/l0 && \
mkdir -p /tmp/tessellation/l0/data/snapshot && \

echo -e "$${blu}[Tessellation]$${clr} Fetching jars, genesis and seedlist" && \

wget https://github.com/Constellation-Labs/tessellation/releases/download/v${tessellation_version}/cl-dag-l1.jar -q -O /tmp/tessellation/l1/cl-dag-l1.jar && \
wget https://github.com/Constellation-Labs/tessellation/releases/download/v${tessellation_version}/cl-node.jar -q -O /tmp/tessellation/l0/cl-node.jar && \
wget https://github.com/Constellation-Labs/tessellation/releases/download/v${tessellation_version}/cl-keytool.jar -q -O /tmp/tessellation/cl-keytool.jar && \
# wget https://constellationlabs-dag.s3.amazonaws.com/keys_v2/${key} -q -O /tmp/tessellation/key.p12 && \
wget https://constellationlabs-dag.s3.amazonaws.com/keys_v2/data.csv -q -O /tmp/tessellation/l0/genesis.csv && \
wget https://constellationlabs-dag.s3.us-west-1.amazonaws.com/${app_env}-seedlist -q -O /tmp/tessellation/l0/${app_env}-seedlist && \

echo -e "$${blu}[Tessellation]$${clr} Setting up scripts for cluster"
cp /tmp/restart-cluster /tmp/tessellation

echo -e "$${blu}[Tessellation]$${clr} Setting up scripts for l0"

cp -R /tmp/l0 /tmp/tessellation && \
cp /tmp/update-seedlist /tmp/tessellation/l0/update-seedlist && \
cp /tmp/snapshots-s3-sync /tmp/tessellation/l0/snapshots-s3-sync && \
cp /tmp/key.p12 /tmp/tessellation/l0/key.p12 && \

echo -e "$${blu}[Tessellation]$${clr} Setting up scripts for l1" && \

cp -R /tmp/l1 /tmp/tessellation && \
cp /tmp/key.p12 /tmp/tessellation/l1/key.p12 && \

echo -e "$${blu}[Tessellation]$${clr} Giving privileges" && \

sudo mv /tmp/tessellation /home/admin && \

sudo chmod u+x /home/${user}/tessellation/restart-cluster && \

sudo chmod u+x /home/${user}/tessellation/l0/run-rollback && \
sudo chmod u+x /home/${user}/tessellation/l0/run-genesis && \
sudo chmod u+x /home/${user}/tessellation/l0/run-validator && \
sudo chmod u+x /home/${user}/tessellation/l0/join && \
sudo chmod u+x /home/${user}/tessellation/l0/restart && \
sudo chmod u+x /home/${user}/tessellation/l0/update-seedlist && \
sudo chmod u+x /home/${user}/tessellation/l0/update-version && \
sudo chmod u+x /home/${user}/tessellation/l0/snapshots-s3-sync && \
sudo ln -s /home/${user}/tessellation/l0/run-validator /home/${user}/tessellation/l0/start  && \

sudo chmod u+x /home/${user}/tessellation/l1/join && \
sudo chmod u+x /home/${user}/tessellation/l1/restart && \
sudo chmod u+x /home/${user}/tessellation/l1/run-initial-validator && \
sudo chmod u+x /home/${user}/tessellation/l1/run-validator && \
sudo ln -s /home/${user}/tessellation/l1/run-validator /home/${user}/tessellation/l1/start && \

sudo chown -R admin:admin /home/${user}/tessellation && \

echo -e "$${blu}[Tessellation]$${clr} Node setup succeeded" || \
echo -e "$${red}[Tessellation]$${clr} Node setup failed!"
