#!/usr/bin/env bash

red='\033[1;31m'
blu='\033[1;36m'
clr='\033[0m'

setup_service() {
    echo -e "$${blu}[Tessellation]$${clr} Linking $1.service..." && \
    sudo chmod 774 /home/${user}/tessellation/$1/$1.service && \
    sudo systemctl link /home/${user}/tessellation/$1/$1.service && \
    sudo systemctl daemon-reload || \
    echo -e "$${red}[Tessellation]$${clr} Failed to link $1.service!"
}

setup_service "l1"
setup_service "l0"
