#!/bin/sh

echo "[Tessellation] S3 sync setup started..." && \
export AWS_ACCESS_KEY_ID=${bucket_access_key}  && \
export AWS_SECRET_ACCESS_KEY=${bucket_secret_key}  && \

/usr/bin/aws s3 sync /home/admin/tessellation/l0/${snapshot_stored_path} ${bucket_name}  && \
echo "[Tessellation] S3 sync setup succeeded"  || \
echo "[Tessellation] S3 sync setup failed!"