#!/bin/bash

VERSION=$1

wget https://github.com/Constellation-Labs/tessellation/releases/download/$VERSION/cl-node.jar -O cl-node.jar
wget https://github.com/Constellation-Labs/tessellation/releases/download/$VERSION/cl-dag-l1.jar -O cl-dag-l1.jar
