#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

mv -v /home/${user}/tessellation/l0/logs /home/${user}/tessellation/l0/logs_$(date +"%Y-%m-%dT%H:%M:%SZ") 2>/dev/null
/home/${user}/tessellation/l0/update-seedlist
systemctl restart l0
